name: personal_finance_manager
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3+1
  uuid: ^4.5.1
  path: ^1.9.0
  gap: ^3.0.1
  go_router: ^14.6.0
  flutter_bloc: ^8.1.6
  vector_graphics: ^1.1.14
  iconsax: ^0.0.8

dev_dependencies:
  vector_graphics_compiler: ^1.1.14
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/rasters/
    - path: assets/vectors/
      transformers:
        - package: vector_graphics_compiler
